{% set name = "TA-Lib" %}
{% set version = "0.4.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: 948001ca61672b4eeef12a8cc9e8c59b

build:
  number: 0
  skip: true # [py<37 or not x86_64]
  include_recipe: False

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools_scm
    - cython
    - numpy >=1.15 [py==37]
    - numpy >=1.18 [py==38]
    - numpy >=1.21 [py==39]
    - numpy >=1.23 [py==310]

  run:
    - python
    - numpy

test:
  requires:
    - numpy
    - Cython
    - pytest
    - pandas
    - polars
    - pytest
  imports:
    - talib
  commands:
    - pytest

about:
  home: http://github.com/mrjbq7/ta-lib
  license: BSD License
