CONDA_BUILD_SYSROOT:
  - /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk # [osx]

numpy:
  - 1.16
  - 1.18
  - 1.21
  - 1.23

python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10

zip_keys:
  - python
  - numpy