name: Build and Publish Python Package (Poetry-compatible token)

on:
  release:
    types: [published]

permissions:
  contents: write  # Required for uploading release assets

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: publishing
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Build on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install cibuildwheel and build tools
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel twine build

    - name: Build binary wheels with cibuildwheel
      run: cibuildwheel --output-dir dist
      env:
        CIBW_SKIP: "*-musllinux*"

    - name: Build source distribution (sdist)
      if: matrix.os == 'ubuntu-latest'
      run: python -m build --sdist --outdir dist

    - name: Upload artifacts to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*

    - name: Publish to PyPI with Poetry-compatible token
      if: matrix.os == 'ubuntu-latest'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*